version: "3.6"
services:
  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=tintuc_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123123
    ports:
      - '3306:3306'

  web:
    build: ./playground
    restart: always
    ports:
      - '9999:80'
    volumes:
      - ./playground/src:/var/www/html
    environment:
        # These password and stuff is not neccesarry too secret
        - MYSQL_HOSTNAME=db
        - MYSQL_ROOT_PASSWORD=123123
        - MYSQL_DATABASE=tintuc_db
        - MYSQL_USER=user
        - MYSQL_PASSWORD=123123
